### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by Morbius00**
Open Source Love 
## Readme.md Update
* added some important badges
* Changed and add some git codes for make the pr more easier
* added my profile in Contributor.md

### CODE REVIEW

**Comment by Morbius00** [comment]
hey thanks for the merged .
but do you have any idea why my 1st pr is not showing in my hacktober fest22 website
I think you have to add the hacktober fest lable in this pr 
please check out this issue

**Comment by Morbius00** [comment]
your project is excluded from hactober fest check your issues

**Comment by Anisha7860** [comment]
I have added the label , ig the repository is not considered under
hacktoberfest.
You can contribute to my another repo.

**Comment by Anisha7860** [comment]
Thanks, I'll check it out.

**Pull request merged**
